# https://gist.github.com/rothgar/8793800
# tasks/hosts.yml
- name: Generate /etc/hosts file
  hosts: servers

  vars:
    - localdomain: intra

  tasks:
    - debug: msg="{{ groups }}"
    - debug: msg="{{ groups['servers'] }}"
    - template:
        src: hosts.j2
        dest: /etc/hosts