---
- hosts: localhost
  gather_facts: no
  become: false
  vars:
    target_dir: /var
    rsyslog_conf_file: opt

  tasks:
  - name: Check for existing config files
    shell: ls {{ target_dir }} # noqa 305
    register: capture
    changed_when: false
  - name: Show register
    debug:
      msg: "{{ capture.stdout_lines }}"
  - name: Remove unexpected rsyslog config files
    debug:
     msg: path={{ target_dir }}/{{ item }} state=absent
    with_items: "{{ capture.stdout_lines }}"
    when: item != rsyslog_conf_file
    ignore_errors: True